//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public string Category { get; set; }
        public string Desc { get; set; }
        public string Src { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
